/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IngresoView.java
 *
 * 
 */

package view;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.*;
import control.*;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Administrador
 */
public class IngresoView extends javax.swing.JFrame {
    private Persona persona;
    private JLabel lblFoto;

    /** Creates new form IngresoView */
    public IngresoView() {
        initComponents();
        
        persona= new Persona();
              
        this.setLocationRelativeTo(null);

        
        jLabel5.setIcon(new javax.swing.ImageIcon("fotos\\foto5.jpg"));
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfRut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfFono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfFoto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESO DE DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        btnAgregar.setText("Grabar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 70, 20));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel2.setText("Rut:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jtfRut.setColumns(10);
        jtfRut.setToolTipText("Ingresar rut con guión y digito verificador");
        jtfRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfRutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRutFocusLost(evt);
            }
        });
        jtfRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRutActionPerformed(evt);
            }
        });
        jtfRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRutKeyTyped(evt);
            }
        });
        getContentPane().add(jtfRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 86, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, -1));

        jLabel4.setText("Fono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jtfFono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfFonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfFonoFocusLost(evt);
            }
        });
        getContentPane().add(jtfFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 86, -1));

        jLabel5.setText("<  foto  >");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, 110));

        jLabel6.setText("Foto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(jtfFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, 380, 80));

        jLabel7.setText("Visor:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jButton6.setText("Listar");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel8.setText("Género:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Femenino");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Masculino");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel9.setText("Carrera:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaria", "Contador", "Ingeniero Inf.", "Analista", "Auditor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
      boolean gen=false;
      
      if(jRadioButton1.isSelected()==true)
      {
         gen=false; //femenino
      }
      if(jRadioButton2.isSelected()==true)
      {
         gen=true;//masculino
      }
        
        
      String rut=jtfRut.getText();
      String nombre=jtfNombre.getText();
      boolean genero=gen;
      String carrera=jComboBox1.getSelectedItem().toString();
      String fono=jtfFono.getText();
      String foto=jtfFoto.getText();
      
        
      if(!rut.equals("")  &&  !nombre.equals("") &&        
              !fono.equals("") && !foto.equals(""))
      {  
        persona=new Persona(rut,nombre,genero,carrera,fono,foto);
        try {
            PersonaDB.agregar(persona);
            limpiar();
        } catch (Exception ex) {
           // Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Error de acceso a base de datos...");
            
        }
      }
      else
          JOptionPane.showMessageDialog(null, "Registro en blanco...");
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Metodo que permite consultar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         
      if(!jtfRut.getText().equals(""))
      {     
        try
        {
             persona=PersonaDB.buscar(jtfRut.getText());
             
             if(!(persona.getRut()==null))
                 actualizar();
             else
                 limpiar();
          
        } catch (Exception ex) {
            //Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error con acceso a base de datos...");
        }
      }
      else
           JOptionPane.showMessageDialog(null, "Registro en blanco...");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
      
      if(!jtfRut.getText().equals(""))
      {  
        
        String respuesta = String.valueOf(JOptionPane.showConfirmDialog(this,"¿Está Seguro que desea eliminar este registro","¿Segur@ de Eliminar?",JOptionPane.YES_NO_OPTION ));
        if(respuesta.equals( String.valueOf(JOptionPane.YES_OPTION )) )
        {
                      
           try {
                  PersonaDB.eliminar(jtfRut.getText());
                  limpiar();
               } catch (Exception ex) {
                     // Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error con acceso a base de datos...");
               }
            
        }
      }
      else
           JOptionPane.showMessageDialog(null, "Registro en blanco...");
        
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      boolean gen=false;
      
      if(jRadioButton1.isSelected()==true)
      {
         gen=false; //femenino
      }
      if(jRadioButton2.isSelected()==true)
      {
         gen=true;//masculino
      }       
    
        
      if(!jtfRut.getText().equals(""))
      {    
        persona=new Persona(jtfRut.getText(),
                            jtfNombre.getText(),
                            gen,
                            jComboBox1.getSelectedItem().toString(),
                            jtfFono.getText(),
                            jtfFoto.getText());
        try
        {
            PersonaDB.modificar(persona);
            limpiar();
        } catch (Exception ex) {
           // Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Error con el acceso a la base de datos...");
        }
      }
      else
          JOptionPane.showMessageDialog(null, "Registro en blanco...");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusGained
        // TODO add your handling code here:
        jtfNombre.setBackground(Color.yellow);
    }//GEN-LAST:event_jtfNombreFocusGained

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        // TODO add your handling code here:
        jtfNombre.setBackground(Color.white);
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRutKeyTyped
        // TODO add your handling code here:
        if(jtfRut.getText().length()>=10)
            evt.consume();
    }//GEN-LAST:event_jtfRutKeyTyped

    private void jtfFonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFonoFocusGained
        // TODO add your handling code here:
        jtfFono.setBackground(Color.yellow);
    }//GEN-LAST:event_jtfFonoFocusGained

    private void jtfFonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFonoFocusLost
        // TODO add your handling code here:
        jtfFono.setBackground(Color.white);
    }//GEN-LAST:event_jtfFonoFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        jTextArea1.setText("");
        try{
            
          for(Persona  obj:PersonaDB.listar())
          {
           jTextArea1.append(obj.toString()+"\n");
          }
        }
        catch(Exception ev)
        {
        
        }
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtfRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRutActionPerformed

    private void jtfRutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRutFocusGained
        // TODO add your handling code here:
        jtfRut.setBackground(Color.yellow);
    }//GEN-LAST:event_jtfRutFocusGained

    private void jtfRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRutFocusLost
        // TODO add your handling code here:
        jtfRut.setBackground(Color.white);
    }//GEN-LAST:event_jtfRutFocusLost

    private void Combo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo





   public void actualizar (){
        
       // JOptionPane.showMessageDialog(null,"Act"+persona.toString());
        jtfRut.setText(persona.getRut());
        jtfNombre.setText(persona.getNombre());
        
        if(persona.isGenero())
        {
           jRadioButton2.setSelected(true);
        }   
        else
        {
           jRadioButton1.setSelected(true);
        }
        
        jComboBox1.setSelectedItem(persona.getCarrera());
        jtfFono.setText(persona.getFono());
        jtfFoto.setText(persona.getFoto());
        if(!persona.getFoto().equals(""))
            jLabel5.setIcon(new javax.swing.ImageIcon("fotos\\"+persona.getFoto()));
        //super.setVisible(true);
        //
        
   }
   
  public void limpiar(){
        jtfRut.setText("");
        jtfNombre.setText("");
        jtfFono.setText("");
        jtfFoto.setText("");
        setVisible(true);
       
  }

  public static void main(String[] arg ){

     new IngresoView().setVisible(true);
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtfFono;
    private javax.swing.JTextField jtfFoto;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRut;
    // End of variables declaration//GEN-END:variables

}
